name: Commit checker

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
    - name: Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        arch: x86
        disable-animations: true
        script: ./gradlew connectedCheck --stacktrace
    - name: Upload Reports
      run: bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"
