name: master

on:
  push:
    branches:
      - 'master'

jobs:
  Release:
    name: Release Version
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace
      - name: Create Test Report
        run: bash ./gradlew jacocoTestReport --stacktrace
      - name: Upload Reports
        run: bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"
      - name: Release version
        run: bash ./gradlew release --stacktrace -PghToken=$GH_TOKEN


