name: splash_screen

on:
  push:
    branches:
      - 'splash_screen'

jobs:
  Release:
    name: Test
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
        with:
          java-version: 1.8
      - name: Release version
        run: bash ./gradlew release --stacktrace -PghToken="$GH_TOKEN" -PBINTRAY_APIKEY="$BINTRAY_APIKEY" -PBINTRAY_USER="$BINTRAY_USER" -PCODECOV_TOKEN="$CODECOV_TOKEN"
      - name: Release version
        run: echo "$BINTRAY_APIKEY"


